# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Sonar Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: 'go.mod'

      - name: Generate Sonar Report
        run: go test -coverpkg=./... -coverprofile=coverage.out -timeout=5m -json ./... > sonar-report.json

      - name: Upload coverage reports to Sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        if: github.event.pull_request.head.repo.full_name == github.repository || env.SONAR_TOKEN != ''
        uses: SonarSource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f # v8.2.1