name: Sonar Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Generate Sonar Report
        run: go test -coverpkg=./... -coverprofile=coverage.out -json ./... > sonar-report.json

      - name: Upload coverage reports to Sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        if: github.event.pull_request.head.repo.full_name == github.repository || env.SONAR_TOKEN != ''
        uses: sonarsource/sonarcloud-github-action@master